/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MethodologyHeadRouteImport } from './routes/methodology.head'
import { Route as MarketHeadRouteImport } from './routes/market.head'
import { Route as IndexHeadRouteImport } from './routes/index.head'
import { Route as DocsMarketTreatmentsRouteImport } from './routes/docs.market-treatments'
import { Route as DocsMarketOverviewRouteImport } from './routes/docs.market-overview'
import { Route as DocsMarketActivityRouteImport } from './routes/docs.market-activity'
import { Route as DocsCardsHistoryRouteImport } from './routes/docs.cards-history'
import { Route as DocsCardsDetailRouteImport } from './routes/docs.cards-detail'
import { Route as DocsCardsActiveRouteImport } from './routes/docs.cards-active'
import { Route as DocsCardsRouteImport } from './routes/docs.cards'
import { Route as DocsBlokpaxSummaryRouteImport } from './routes/docs.blokpax-summary'
import { Route as DocsBlokpaxStorefrontsRouteImport } from './routes/docs.blokpax-storefronts'
import { Route as DocsBlokpaxSalesRouteImport } from './routes/docs.blokpax-sales'
import { Route as DocsBlokpaxOffersRouteImport } from './routes/docs.blokpax-offers'
import { Route as DocsAuthenticationRouteImport } from './routes/docs.authentication'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'
import { Route as BlogWeeklyMoversRouteImport } from './routes/blog.weekly-movers'
import { Route as BlogMarketInsightsRouteImport } from './routes/blog.market-insights'
import { Route as BlogHeadRouteImport } from './routes/blog.head'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminScrapersRouteImport } from './routes/admin.scrapers'
import { Route as AdminMarketRouteImport } from './routes/admin.market'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as BlogWeeklyMoversIndexRouteImport } from './routes/blog.weekly-movers.index'
import { Route as CardsCardIdHeadRouteImport } from './routes/cards.$cardId.head'
import { Route as BlogWeeklyMoversDateRouteImport } from './routes/blog.weekly-movers.$date'
import { Route as BlogSlugHeadRouteImport } from './routes/blog.$slug.head'
import { Route as BlogWeeklyMoversDateHeadRouteImport } from './routes/blog.weekly-movers.$date.head'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MethodologyHeadRoute = MethodologyHeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => MethodologyRoute,
} as any)
const MarketHeadRoute = MarketHeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => MarketRoute,
} as any)
const IndexHeadRoute = IndexHeadRouteImport.update({
  id: '/index/head',
  path: '/index/head',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMarketTreatmentsRoute = DocsMarketTreatmentsRouteImport.update({
  id: '/market-treatments',
  path: '/market-treatments',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMarketOverviewRoute = DocsMarketOverviewRouteImport.update({
  id: '/market-overview',
  path: '/market-overview',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMarketActivityRoute = DocsMarketActivityRouteImport.update({
  id: '/market-activity',
  path: '/market-activity',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCardsHistoryRoute = DocsCardsHistoryRouteImport.update({
  id: '/cards-history',
  path: '/cards-history',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCardsDetailRoute = DocsCardsDetailRouteImport.update({
  id: '/cards-detail',
  path: '/cards-detail',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCardsActiveRoute = DocsCardsActiveRouteImport.update({
  id: '/cards-active',
  path: '/cards-active',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCardsRoute = DocsCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBlokpaxSummaryRoute = DocsBlokpaxSummaryRouteImport.update({
  id: '/blokpax-summary',
  path: '/blokpax-summary',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBlokpaxStorefrontsRoute = DocsBlokpaxStorefrontsRouteImport.update({
  id: '/blokpax-storefronts',
  path: '/blokpax-storefronts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBlokpaxSalesRoute = DocsBlokpaxSalesRouteImport.update({
  id: '/blokpax-sales',
  path: '/blokpax-sales',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBlokpaxOffersRoute = DocsBlokpaxOffersRouteImport.update({
  id: '/blokpax-offers',
  path: '/blokpax-offers',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAuthenticationRoute = DocsAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => DocsRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWeeklyMoversRoute = BlogWeeklyMoversRouteImport.update({
  id: '/weekly-movers',
  path: '/weekly-movers',
  getParentRoute: () => BlogRoute,
} as any)
const BlogMarketInsightsRoute = BlogMarketInsightsRouteImport.update({
  id: '/market-insights',
  path: '/market-insights',
  getParentRoute: () => BlogRoute,
} as any)
const BlogHeadRoute = BlogHeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScrapersRoute = AdminScrapersRouteImport.update({
  id: '/scrapers',
  path: '/scrapers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketRoute = AdminMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const BlogWeeklyMoversIndexRoute = BlogWeeklyMoversIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogWeeklyMoversRoute,
} as any)
const CardsCardIdHeadRoute = CardsCardIdHeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => CardsCardIdRoute,
} as any)
const BlogWeeklyMoversDateRoute = BlogWeeklyMoversDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => BlogWeeklyMoversRoute,
} as any)
const BlogSlugHeadRoute = BlogSlugHeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => BlogSlugRoute,
} as any)
const BlogWeeklyMoversDateHeadRoute =
  BlogWeeklyMoversDateHeadRouteImport.update({
    id: '/head',
    path: '/head',
    getParentRoute: () => BlogWeeklyMoversDateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api': typeof ApiRoute
  '/blog': typeof BlogRouteWithChildren
  '/browse': typeof BrowseRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/methodology': typeof MethodologyRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/market': typeof AdminMarketRoute
  '/admin/scrapers': typeof AdminScrapersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog/head': typeof BlogHeadRoute
  '/blog/market-insights': typeof BlogMarketInsightsRoute
  '/blog/weekly-movers': typeof BlogWeeklyMoversRouteWithChildren
  '/cards/$cardId': typeof CardsCardIdRouteWithChildren
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/blokpax-offers': typeof DocsBlokpaxOffersRoute
  '/docs/blokpax-sales': typeof DocsBlokpaxSalesRoute
  '/docs/blokpax-storefronts': typeof DocsBlokpaxStorefrontsRoute
  '/docs/blokpax-summary': typeof DocsBlokpaxSummaryRoute
  '/docs/cards': typeof DocsCardsRoute
  '/docs/cards-active': typeof DocsCardsActiveRoute
  '/docs/cards-detail': typeof DocsCardsDetailRoute
  '/docs/cards-history': typeof DocsCardsHistoryRoute
  '/docs/market-activity': typeof DocsMarketActivityRoute
  '/docs/market-overview': typeof DocsMarketOverviewRoute
  '/docs/market-treatments': typeof DocsMarketTreatmentsRoute
  '/index/head': typeof IndexHeadRoute
  '/market/head': typeof MarketHeadRoute
  '/methodology/head': typeof MethodologyHeadRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/blog/$slug/head': typeof BlogSlugHeadRoute
  '/blog/weekly-movers/$date': typeof BlogWeeklyMoversDateRouteWithChildren
  '/cards/$cardId/head': typeof CardsCardIdHeadRoute
  '/blog/weekly-movers/': typeof BlogWeeklyMoversIndexRoute
  '/blog/weekly-movers/$date/head': typeof BlogWeeklyMoversDateHeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/browse': typeof BrowseRoute
  '/changelog': typeof ChangelogRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/methodology': typeof MethodologyRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/market': typeof AdminMarketRoute
  '/admin/scrapers': typeof AdminScrapersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog/head': typeof BlogHeadRoute
  '/blog/market-insights': typeof BlogMarketInsightsRoute
  '/cards/$cardId': typeof CardsCardIdRouteWithChildren
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/blokpax-offers': typeof DocsBlokpaxOffersRoute
  '/docs/blokpax-sales': typeof DocsBlokpaxSalesRoute
  '/docs/blokpax-storefronts': typeof DocsBlokpaxStorefrontsRoute
  '/docs/blokpax-summary': typeof DocsBlokpaxSummaryRoute
  '/docs/cards': typeof DocsCardsRoute
  '/docs/cards-active': typeof DocsCardsActiveRoute
  '/docs/cards-detail': typeof DocsCardsDetailRoute
  '/docs/cards-history': typeof DocsCardsHistoryRoute
  '/docs/market-activity': typeof DocsMarketActivityRoute
  '/docs/market-overview': typeof DocsMarketOverviewRoute
  '/docs/market-treatments': typeof DocsMarketTreatmentsRoute
  '/index/head': typeof IndexHeadRoute
  '/market/head': typeof MarketHeadRoute
  '/methodology/head': typeof MethodologyHeadRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/blog/$slug/head': typeof BlogSlugHeadRoute
  '/blog/weekly-movers/$date': typeof BlogWeeklyMoversDateRouteWithChildren
  '/cards/$cardId/head': typeof CardsCardIdHeadRoute
  '/blog/weekly-movers': typeof BlogWeeklyMoversIndexRoute
  '/blog/weekly-movers/$date/head': typeof BlogWeeklyMoversDateHeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api': typeof ApiRoute
  '/blog': typeof BlogRouteWithChildren
  '/browse': typeof BrowseRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/methodology': typeof MethodologyRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/market': typeof AdminMarketRoute
  '/admin/scrapers': typeof AdminScrapersRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRouteWithChildren
  '/blog/head': typeof BlogHeadRoute
  '/blog/market-insights': typeof BlogMarketInsightsRoute
  '/blog/weekly-movers': typeof BlogWeeklyMoversRouteWithChildren
  '/cards/$cardId': typeof CardsCardIdRouteWithChildren
  '/docs/authentication': typeof DocsAuthenticationRoute
  '/docs/blokpax-offers': typeof DocsBlokpaxOffersRoute
  '/docs/blokpax-sales': typeof DocsBlokpaxSalesRoute
  '/docs/blokpax-storefronts': typeof DocsBlokpaxStorefrontsRoute
  '/docs/blokpax-summary': typeof DocsBlokpaxSummaryRoute
  '/docs/cards': typeof DocsCardsRoute
  '/docs/cards-active': typeof DocsCardsActiveRoute
  '/docs/cards-detail': typeof DocsCardsDetailRoute
  '/docs/cards-history': typeof DocsCardsHistoryRoute
  '/docs/market-activity': typeof DocsMarketActivityRoute
  '/docs/market-overview': typeof DocsMarketOverviewRoute
  '/docs/market-treatments': typeof DocsMarketTreatmentsRoute
  '/index/head': typeof IndexHeadRoute
  '/market/head': typeof MarketHeadRoute
  '/methodology/head': typeof MethodologyHeadRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/blog/$slug/head': typeof BlogSlugHeadRoute
  '/blog/weekly-movers/$date': typeof BlogWeeklyMoversDateRouteWithChildren
  '/cards/$cardId/head': typeof CardsCardIdHeadRoute
  '/blog/weekly-movers/': typeof BlogWeeklyMoversIndexRoute
  '/blog/weekly-movers/$date/head': typeof BlogWeeklyMoversDateHeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api'
    | '/blog'
    | '/browse'
    | '/changelog'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/methodology'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/upgrade'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/market'
    | '/admin/scrapers'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/head'
    | '/blog/market-insights'
    | '/blog/weekly-movers'
    | '/cards/$cardId'
    | '/docs/authentication'
    | '/docs/blokpax-offers'
    | '/docs/blokpax-sales'
    | '/docs/blokpax-storefronts'
    | '/docs/blokpax-summary'
    | '/docs/cards'
    | '/docs/cards-active'
    | '/docs/cards-detail'
    | '/docs/cards-history'
    | '/docs/market-activity'
    | '/docs/market-overview'
    | '/docs/market-treatments'
    | '/index/head'
    | '/market/head'
    | '/methodology/head'
    | '/admin/'
    | '/blog/'
    | '/docs/'
    | '/blog/$slug/head'
    | '/blog/weekly-movers/$date'
    | '/cards/$cardId/head'
    | '/blog/weekly-movers/'
    | '/blog/weekly-movers/$date/head'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/browse'
    | '/changelog'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/methodology'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/upgrade'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/market'
    | '/admin/scrapers'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/head'
    | '/blog/market-insights'
    | '/cards/$cardId'
    | '/docs/authentication'
    | '/docs/blokpax-offers'
    | '/docs/blokpax-sales'
    | '/docs/blokpax-storefronts'
    | '/docs/blokpax-summary'
    | '/docs/cards'
    | '/docs/cards-active'
    | '/docs/cards-detail'
    | '/docs/cards-history'
    | '/docs/market-activity'
    | '/docs/market-overview'
    | '/docs/market-treatments'
    | '/index/head'
    | '/market/head'
    | '/methodology/head'
    | '/admin'
    | '/blog'
    | '/docs'
    | '/blog/$slug/head'
    | '/blog/weekly-movers/$date'
    | '/cards/$cardId/head'
    | '/blog/weekly-movers'
    | '/blog/weekly-movers/$date/head'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api'
    | '/blog'
    | '/browse'
    | '/changelog'
    | '/docs'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/methodology'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/upgrade'
    | '/welcome'
    | '/admin/analytics'
    | '/admin/api-keys'
    | '/admin/market'
    | '/admin/scrapers'
    | '/admin/users'
    | '/auth/callback'
    | '/blog/$slug'
    | '/blog/head'
    | '/blog/market-insights'
    | '/blog/weekly-movers'
    | '/cards/$cardId'
    | '/docs/authentication'
    | '/docs/blokpax-offers'
    | '/docs/blokpax-sales'
    | '/docs/blokpax-storefronts'
    | '/docs/blokpax-summary'
    | '/docs/cards'
    | '/docs/cards-active'
    | '/docs/cards-detail'
    | '/docs/cards-history'
    | '/docs/market-activity'
    | '/docs/market-overview'
    | '/docs/market-treatments'
    | '/index/head'
    | '/market/head'
    | '/methodology/head'
    | '/admin/'
    | '/blog/'
    | '/docs/'
    | '/blog/$slug/head'
    | '/blog/weekly-movers/$date'
    | '/cards/$cardId/head'
    | '/blog/weekly-movers/'
    | '/blog/weekly-movers/$date/head'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiRoute: typeof ApiRoute
  BlogRoute: typeof BlogRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRouteWithChildren
  MethodologyRoute: typeof MethodologyRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  UpgradeRoute: typeof UpgradeRoute
  WelcomeRoute: typeof WelcomeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CardsCardIdRoute: typeof CardsCardIdRouteWithChildren
  IndexHeadRoute: typeof IndexHeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/methodology/head': {
      id: '/methodology/head'
      path: '/head'
      fullPath: '/methodology/head'
      preLoaderRoute: typeof MethodologyHeadRouteImport
      parentRoute: typeof MethodologyRoute
    }
    '/market/head': {
      id: '/market/head'
      path: '/head'
      fullPath: '/market/head'
      preLoaderRoute: typeof MarketHeadRouteImport
      parentRoute: typeof MarketRoute
    }
    '/index/head': {
      id: '/index/head'
      path: '/index/head'
      fullPath: '/index/head'
      preLoaderRoute: typeof IndexHeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/market-treatments': {
      id: '/docs/market-treatments'
      path: '/market-treatments'
      fullPath: '/docs/market-treatments'
      preLoaderRoute: typeof DocsMarketTreatmentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/market-overview': {
      id: '/docs/market-overview'
      path: '/market-overview'
      fullPath: '/docs/market-overview'
      preLoaderRoute: typeof DocsMarketOverviewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/market-activity': {
      id: '/docs/market-activity'
      path: '/market-activity'
      fullPath: '/docs/market-activity'
      preLoaderRoute: typeof DocsMarketActivityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cards-history': {
      id: '/docs/cards-history'
      path: '/cards-history'
      fullPath: '/docs/cards-history'
      preLoaderRoute: typeof DocsCardsHistoryRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cards-detail': {
      id: '/docs/cards-detail'
      path: '/cards-detail'
      fullPath: '/docs/cards-detail'
      preLoaderRoute: typeof DocsCardsDetailRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cards-active': {
      id: '/docs/cards-active'
      path: '/cards-active'
      fullPath: '/docs/cards-active'
      preLoaderRoute: typeof DocsCardsActiveRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cards': {
      id: '/docs/cards'
      path: '/cards'
      fullPath: '/docs/cards'
      preLoaderRoute: typeof DocsCardsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/blokpax-summary': {
      id: '/docs/blokpax-summary'
      path: '/blokpax-summary'
      fullPath: '/docs/blokpax-summary'
      preLoaderRoute: typeof DocsBlokpaxSummaryRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/blokpax-storefronts': {
      id: '/docs/blokpax-storefronts'
      path: '/blokpax-storefronts'
      fullPath: '/docs/blokpax-storefronts'
      preLoaderRoute: typeof DocsBlokpaxStorefrontsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/blokpax-sales': {
      id: '/docs/blokpax-sales'
      path: '/blokpax-sales'
      fullPath: '/docs/blokpax-sales'
      preLoaderRoute: typeof DocsBlokpaxSalesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/blokpax-offers': {
      id: '/docs/blokpax-offers'
      path: '/blokpax-offers'
      fullPath: '/docs/blokpax-offers'
      preLoaderRoute: typeof DocsBlokpaxOffersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/authentication': {
      id: '/docs/authentication'
      path: '/authentication'
      fullPath: '/docs/authentication'
      preLoaderRoute: typeof DocsAuthenticationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/weekly-movers': {
      id: '/blog/weekly-movers'
      path: '/weekly-movers'
      fullPath: '/blog/weekly-movers'
      preLoaderRoute: typeof BlogWeeklyMoversRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/market-insights': {
      id: '/blog/market-insights'
      path: '/market-insights'
      fullPath: '/blog/market-insights'
      preLoaderRoute: typeof BlogMarketInsightsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/head': {
      id: '/blog/head'
      path: '/head'
      fullPath: '/blog/head'
      preLoaderRoute: typeof BlogHeadRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scrapers': {
      id: '/admin/scrapers'
      path: '/scrapers'
      fullPath: '/admin/scrapers'
      preLoaderRoute: typeof AdminScrapersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/market': {
      id: '/admin/market'
      path: '/market'
      fullPath: '/admin/market'
      preLoaderRoute: typeof AdminMarketRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/weekly-movers/': {
      id: '/blog/weekly-movers/'
      path: '/'
      fullPath: '/blog/weekly-movers/'
      preLoaderRoute: typeof BlogWeeklyMoversIndexRouteImport
      parentRoute: typeof BlogWeeklyMoversRoute
    }
    '/cards/$cardId/head': {
      id: '/cards/$cardId/head'
      path: '/head'
      fullPath: '/cards/$cardId/head'
      preLoaderRoute: typeof CardsCardIdHeadRouteImport
      parentRoute: typeof CardsCardIdRoute
    }
    '/blog/weekly-movers/$date': {
      id: '/blog/weekly-movers/$date'
      path: '/$date'
      fullPath: '/blog/weekly-movers/$date'
      preLoaderRoute: typeof BlogWeeklyMoversDateRouteImport
      parentRoute: typeof BlogWeeklyMoversRoute
    }
    '/blog/$slug/head': {
      id: '/blog/$slug/head'
      path: '/head'
      fullPath: '/blog/$slug/head'
      preLoaderRoute: typeof BlogSlugHeadRouteImport
      parentRoute: typeof BlogSlugRoute
    }
    '/blog/weekly-movers/$date/head': {
      id: '/blog/weekly-movers/$date/head'
      path: '/head'
      fullPath: '/blog/weekly-movers/$date/head'
      preLoaderRoute: typeof BlogWeeklyMoversDateHeadRouteImport
      parentRoute: typeof BlogWeeklyMoversDateRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminMarketRoute: typeof AdminMarketRoute
  AdminScrapersRoute: typeof AdminScrapersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminMarketRoute: AdminMarketRoute,
  AdminScrapersRoute: AdminScrapersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogSlugRouteChildren {
  BlogSlugHeadRoute: typeof BlogSlugHeadRoute
}

const BlogSlugRouteChildren: BlogSlugRouteChildren = {
  BlogSlugHeadRoute: BlogSlugHeadRoute,
}

const BlogSlugRouteWithChildren = BlogSlugRoute._addFileChildren(
  BlogSlugRouteChildren,
)

interface BlogWeeklyMoversDateRouteChildren {
  BlogWeeklyMoversDateHeadRoute: typeof BlogWeeklyMoversDateHeadRoute
}

const BlogWeeklyMoversDateRouteChildren: BlogWeeklyMoversDateRouteChildren = {
  BlogWeeklyMoversDateHeadRoute: BlogWeeklyMoversDateHeadRoute,
}

const BlogWeeklyMoversDateRouteWithChildren =
  BlogWeeklyMoversDateRoute._addFileChildren(BlogWeeklyMoversDateRouteChildren)

interface BlogWeeklyMoversRouteChildren {
  BlogWeeklyMoversDateRoute: typeof BlogWeeklyMoversDateRouteWithChildren
  BlogWeeklyMoversIndexRoute: typeof BlogWeeklyMoversIndexRoute
}

const BlogWeeklyMoversRouteChildren: BlogWeeklyMoversRouteChildren = {
  BlogWeeklyMoversDateRoute: BlogWeeklyMoversDateRouteWithChildren,
  BlogWeeklyMoversIndexRoute: BlogWeeklyMoversIndexRoute,
}

const BlogWeeklyMoversRouteWithChildren =
  BlogWeeklyMoversRoute._addFileChildren(BlogWeeklyMoversRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRouteWithChildren
  BlogHeadRoute: typeof BlogHeadRoute
  BlogMarketInsightsRoute: typeof BlogMarketInsightsRoute
  BlogWeeklyMoversRoute: typeof BlogWeeklyMoversRouteWithChildren
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRouteWithChildren,
  BlogHeadRoute: BlogHeadRoute,
  BlogMarketInsightsRoute: BlogMarketInsightsRoute,
  BlogWeeklyMoversRoute: BlogWeeklyMoversRouteWithChildren,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsAuthenticationRoute: typeof DocsAuthenticationRoute
  DocsBlokpaxOffersRoute: typeof DocsBlokpaxOffersRoute
  DocsBlokpaxSalesRoute: typeof DocsBlokpaxSalesRoute
  DocsBlokpaxStorefrontsRoute: typeof DocsBlokpaxStorefrontsRoute
  DocsBlokpaxSummaryRoute: typeof DocsBlokpaxSummaryRoute
  DocsCardsRoute: typeof DocsCardsRoute
  DocsCardsActiveRoute: typeof DocsCardsActiveRoute
  DocsCardsDetailRoute: typeof DocsCardsDetailRoute
  DocsCardsHistoryRoute: typeof DocsCardsHistoryRoute
  DocsMarketActivityRoute: typeof DocsMarketActivityRoute
  DocsMarketOverviewRoute: typeof DocsMarketOverviewRoute
  DocsMarketTreatmentsRoute: typeof DocsMarketTreatmentsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAuthenticationRoute: DocsAuthenticationRoute,
  DocsBlokpaxOffersRoute: DocsBlokpaxOffersRoute,
  DocsBlokpaxSalesRoute: DocsBlokpaxSalesRoute,
  DocsBlokpaxStorefrontsRoute: DocsBlokpaxStorefrontsRoute,
  DocsBlokpaxSummaryRoute: DocsBlokpaxSummaryRoute,
  DocsCardsRoute: DocsCardsRoute,
  DocsCardsActiveRoute: DocsCardsActiveRoute,
  DocsCardsDetailRoute: DocsCardsDetailRoute,
  DocsCardsHistoryRoute: DocsCardsHistoryRoute,
  DocsMarketActivityRoute: DocsMarketActivityRoute,
  DocsMarketOverviewRoute: DocsMarketOverviewRoute,
  DocsMarketTreatmentsRoute: DocsMarketTreatmentsRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface MarketRouteChildren {
  MarketHeadRoute: typeof MarketHeadRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketHeadRoute: MarketHeadRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface MethodologyRouteChildren {
  MethodologyHeadRoute: typeof MethodologyHeadRoute
}

const MethodologyRouteChildren: MethodologyRouteChildren = {
  MethodologyHeadRoute: MethodologyHeadRoute,
}

const MethodologyRouteWithChildren = MethodologyRoute._addFileChildren(
  MethodologyRouteChildren,
)

interface CardsCardIdRouteChildren {
  CardsCardIdHeadRoute: typeof CardsCardIdHeadRoute
}

const CardsCardIdRouteChildren: CardsCardIdRouteChildren = {
  CardsCardIdHeadRoute: CardsCardIdHeadRoute,
}

const CardsCardIdRouteWithChildren = CardsCardIdRoute._addFileChildren(
  CardsCardIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiRoute: ApiRoute,
  BlogRoute: BlogRouteWithChildren,
  BrowseRoute: BrowseRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRouteWithChildren,
  MethodologyRoute: MethodologyRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  UpgradeRoute: UpgradeRoute,
  WelcomeRoute: WelcomeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CardsCardIdRoute: CardsCardIdRouteWithChildren,
  IndexHeadRoute: IndexHeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
