/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketHeadRouteImport } from './routes/market.head'
import { Route as IndexHeadRouteImport } from './routes/index.head'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CardsCardIdHeadRouteImport } from './routes/cards.$cardId.head'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketHeadRoute = MarketHeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => MarketRoute,
} as any)
const IndexHeadRoute = IndexHeadRouteImport.update({
  id: '/index/head',
  path: '/index/head',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdHeadRoute = CardsCardIdHeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => CardsCardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cards/$cardId': typeof CardsCardIdRouteWithChildren
  '/index/head': typeof IndexHeadRoute
  '/market/head': typeof MarketHeadRoute
  '/cards/$cardId/head': typeof CardsCardIdHeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cards/$cardId': typeof CardsCardIdRouteWithChildren
  '/index/head': typeof IndexHeadRoute
  '/market/head': typeof MarketHeadRoute
  '/cards/$cardId/head': typeof CardsCardIdHeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api': typeof ApiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/welcome': typeof WelcomeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cards/$cardId': typeof CardsCardIdRouteWithChildren
  '/index/head': typeof IndexHeadRoute
  '/market/head': typeof MarketHeadRoute
  '/cards/$cardId/head': typeof CardsCardIdHeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/upgrade'
    | '/welcome'
    | '/auth/callback'
    | '/cards/$cardId'
    | '/index/head'
    | '/market/head'
    | '/cards/$cardId/head'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/upgrade'
    | '/welcome'
    | '/auth/callback'
    | '/cards/$cardId'
    | '/index/head'
    | '/market/head'
    | '/cards/$cardId/head'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api'
    | '/forgot-password'
    | '/login'
    | '/market'
    | '/portfolio'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/upgrade'
    | '/welcome'
    | '/auth/callback'
    | '/cards/$cardId'
    | '/index/head'
    | '/market/head'
    | '/cards/$cardId/head'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiRoute: typeof ApiRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UpgradeRoute: typeof UpgradeRoute
  WelcomeRoute: typeof WelcomeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CardsCardIdRoute: typeof CardsCardIdRouteWithChildren
  IndexHeadRoute: typeof IndexHeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/head': {
      id: '/market/head'
      path: '/head'
      fullPath: '/market/head'
      preLoaderRoute: typeof MarketHeadRouteImport
      parentRoute: typeof MarketRoute
    }
    '/index/head': {
      id: '/index/head'
      path: '/index/head'
      fullPath: '/index/head'
      preLoaderRoute: typeof IndexHeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId/head': {
      id: '/cards/$cardId/head'
      path: '/head'
      fullPath: '/cards/$cardId/head'
      preLoaderRoute: typeof CardsCardIdHeadRouteImport
      parentRoute: typeof CardsCardIdRoute
    }
  }
}

interface MarketRouteChildren {
  MarketHeadRoute: typeof MarketHeadRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketHeadRoute: MarketHeadRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface CardsCardIdRouteChildren {
  CardsCardIdHeadRoute: typeof CardsCardIdHeadRoute
}

const CardsCardIdRouteChildren: CardsCardIdRouteChildren = {
  CardsCardIdHeadRoute: CardsCardIdHeadRoute,
}

const CardsCardIdRouteWithChildren = CardsCardIdRoute._addFileChildren(
  CardsCardIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiRoute: ApiRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UpgradeRoute: UpgradeRoute,
  WelcomeRoute: WelcomeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CardsCardIdRoute: CardsCardIdRouteWithChildren,
  IndexHeadRoute: IndexHeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
